name: Tailwind
version: 1.1.1
description: Install Tailwind so it's ready to go
url: https://github.com/edalzell/statamic-tailwind
developer: Erin Dalzell
developer_url: https://silentzconsulting.com
